// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinoAvatar: typeof import('./src/components/TinoAvatar/index.vue')['default']
    TinoButton: typeof import('./src/components/TinoButton/index.vue')['default']
    TinoDialog: typeof import('./src/components/TinoDialog/index.vue')['default']
    TinoForm: typeof import('./src/components/TinoForm/index.vue')['default']
    TinoFormItem: typeof import('./src/components/TinoFormItem/index.vue')['default']
    TinoIcon: typeof import('./src/components/TinoIcon/index.vue')['default']
    TinoInput: typeof import('./src/components/TinoInput/index.vue')['default']
    TinoMenu: typeof import('./src/components/TinoMenu/index.vue')['default']
    TinoMenuItem: typeof import('./src/components/TinoMenuItem/index.vue')['default']
    TinoNavigator: typeof import('./src/components/TinoNavigator/index.vue')['default']
    TinoStatusBar: typeof import('./src/components/TinoStatusBar/index.vue')['default']
    TinoTag: typeof import('./src/components/TinoTag/index.vue')['default']
  }
}
