// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinoButton: typeof import('./src/components/TinoButton/index.vue')['default']
    TinoIcon: typeof import('./src/components/TinoIcon/index.vue')['default']
    TinoTag: typeof import('./src/components/TinoTag/index.vue')['default']
  }
}
